### ISSUE TITLE
Enable the extra Drupal modules

### ISSUE THREAD

**Issue by dashohoxha** [dashohoxha/drupal8#1]
The drupal modules are downloaded like this:
```
drush dl --default-major=8 panels backup_migrate devel imce recaptcha pathauto globalredirect webform logintoboggan admin_menu colorbox goo\
gle_analytics advanced_help rules token link date features ctools captcha
```
But they are not enabled. They should be enabled with `drush en -y ...`

**Comment by dashohoxha** [comment]
But why do we need these extra Drupal modules at all? Drupal8 is supposed to be a solution that works well out of the box (different from Drupal7 where you have to do lots of customization and installations).

If we want to offer a turn-key drupal solution, then maybe we should install OpenAtrium or some other drupal distributions.

@JedMeister

P.S. I have enabled issues on the project Settings, in order to record and discuss what needs to be done,

**Comment by JedMeister** [comment]
Great point @dashohoxha! I will double check with Alon and/or Liraz and get back to you.

Regardless an OpenAtrium appliance would be cool! :smile:

**Comment by dashohoxha** [comment]
I removed them for the time being, and later we can add any extra modules, if there is some good reason for adding them.

**Comment by dashohoxha** [comment]
Extra libraries are not needed as well.
By the way, the path of the libraries in drupal8 is `$WEBROOT/libraries` (see: http://drupal.stackexchange.com/questions/84811/what-are-all-the-directories-for-in-the-new-drupal-8-structure).
